name: Story
description: Créez une nouvelle User Story.
title: "[]"
labels: ["story"]
assignees: []

body:
  - type: markdown
    id: problem_description
    attributes:
      value: |
        ## 📝 Problème à Résoudre
        Veuillez décrire le problème en utilisant l'un des formats suivants:

        - **Récit Utilisateur**: En tant que `type d'utilisateur`, je veux `un objectif/une fonctionnalité` afin de `une raison/un cas d'utilisation`.
        - **Récit de Situation**: Lorsque `situation`, je veux `motivation` afin que `résultat attendu`.
        - **Récit de Problème**: Afin de `résoudre le problème`, nous allons `construire une solution`.
        - **Récit d'Amélioration**: Nous avons `situation actuelle`, nous voulons avoir `situation désirée`.

        ---
  - type: textarea
    id: problem_to_solve
    attributes:
      label: Problème à Résoudre
      placeholder: "Utilisez l'un des formats suivants: Récit Utilisateur, Récit de Situation, Récit de Problème, ou Récit d'Amélioration."
    validations:
      required: true

  - type: markdown
    id: details_description
    attributes:
      value: |
        ## 📋 Détails Supplémentaires
        Fournissez toute information additionnelle, captures d'écran ou exemples pour clarifier la demande.

        ---
  - type: textarea
    id: further_details
    attributes:
      label: Détails Supplémentaires
      placeholder: "Incluez des informations supplémentaires ou téléchargez des fichiers pertinents."
    validations:
      required: false

  - type: markdown
    id: solution_description
    attributes:
      value: |
        ## 💡 Solution Proposée
        Décrivez votre solution suggérée en détail.

        ---
  - type: textarea
    id: proposed_solution
    attributes:
      label: Solution Proposée
      placeholder: "Décrivez la solution que vous proposez."
    validations:
      required: true

  - type: markdown
    id: test_description
    attributes:
      value: |
        ## 🧪 Scénarios de Test (BDD)
        Fournissez des scénarios de test en utilisant le format Behavior-Driven Development (BDD) pour valider la fonctionnalité. Ces scénarios doivent être alignés avec les critères d'acceptation et servir de base pour les tests automatisés.

        ### Exemple:
        ```gherkin
        Fonctionnalité: [Nom de la Fonctionnalité]
          En tant que [type d'utilisateur]
          Je veux [objectif]
          Afin de [bénéfice/valeur]

          Scénario: [Titre du Scénario]
            Étant donné [État initial ou préconditions]
            Quand [Action effectuée par l'utilisateur]
            Alors [Résultat attendu]

          Scénario: [Titre d'un Autre Scénario]
            Étant donné [État initial ou préconditions]
            Quand [Action effectuée par l'utilisateur]
            Alors [Résultat attendu]
        ```

        ---
  - type: textarea
    id: testing
    attributes:
      label: Scénarios de Test
      placeholder: "Incluez des scénarios de test en utilisant la syntaxe Gherkin."
    validations:
      required: true

  - type: markdown
    id: criteria_description
    attributes:
      value: |
        ## ✅ Critères d'Acceptation
        Définissez les exigences pour que cette fonctionnalité soit considérée comme complète du point de vue du client.

        - **Les détails d'implémentation ne sont pas des critères d'acceptation.** Évitez les spécificités concernant le code, les bibliothèques ou les technologies utilisées.
        - **Concentrez-vous sur les attentes du client**: Décrivez ce que la fonctionnalité doit accomplir pour l'utilisateur.
        - **Reflétez les scénarios de test**: Assurez l'alignement entre cette section et les scénarios de test.

        ---
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Critères d'Acceptation
      placeholder: |
        - [ ] Critère 1: La fonctionnalité répond à un besoin spécifique de l'utilisateur.
        - [ ] Critère 2: La fonctionnalité correspond aux scénarios de test décrits.
        - [ ] Critère 3: Les retours des utilisateurs sur l'utilisabilité sont positifs.
    validations:
      required: true